### ISSUE TITLE
No Birthdays or Photos

### ISSUE THREAD

**Issue by chadsaun** [jidn/LDS-org#3]
Do you know why I never get any birthdays or photos?

**Comment by jidn** [comment]
Do you have a code snippet I can look at?

**Comment by chadsaun** [comment]
When I run `python -m lds_org -e unit-membership` every single member has `u'birthdate': None` and `u'photoUrl': u'',`

If I log onto LCR I can see Age and Birthdates 🤔

**Comment by jidn** [comment]
That endpoint doesn't seem to provide it.  However, you can get birthdays from the `birthday-list` endpoint.
`python -m lds_org -e birthday-list`

Photos are in a similar vein.  However, the `photo-url` is a problem with automatic substitution of unit number.  The current logic doesn't work with it.  I'll open another issue.

**Comment by jidn** [comment]
I have a bit of sample code on the [README](https://github.com/jidn/LDS-org#photos) where I show getting a photo.
