### ISSUE TITLE
Auto filling of %@ won't work for all endpoints.

### ISSUE THREAD

**Issue by jidn** [jidn/LDS-org#4]
Most endpoints use `%@` as a marker for unit number, but not all.  This really messes up the logic (see issue #3)

Go through the endpoint and turn all `%` markers into `{}`, `{unit}`, or `{member}` variables.  This will allow people to better understand endpoints.

Change the display of endpoints to see the URL

**Comment by chadsaun** [comment]
Is the pip package updated?  I can't seem to bring in these latest changes with `pip install lds-org --upgrade`

**Comment by jidn** [comment]
https://pypi.python.org/pypi/LDS-org/0.2.0a1

My older test version isn't updating either.  It is marked as an alpha release, but I thought it would update.

**Comment by jidn** [comment]
This worked
$ pip install -U LDS_org==0.2.0a1

**Comment by chadsaun** [comment]
That worked thanks 👍
